const EXAM_DATE = new Date(2026, 8, 13);

const INTRO = {
  base: "Baseado no Anexo I do Edital nº 1/2026 + perfil histórico da banca Consulplan.",
};

const PERFIL_BANCA = [
  { area: "Direito / Legislação", texto: "Cobrança <strong>literal da letra de lei</strong>, raramente doutrina ou jurisprudência pesada." },
  { area: "Português", texto: "Interpretação de texto é o carro-chefe, seguido de sintaxe/morfologia." },
  { area: "Raciocínio Lógico", texto: "Resolvido em boa parte com fórmulas diretas — decoreba de fórmula rende muito." },
  { area: "Informática", texto: "Foco em <strong>Windows</strong> e pacote de escritório, não costuma ser complexa." },
  { area: "Cargo (TI)", texto: "Mistura teoria clássica (SO, redes, BD) com tópicos novos do edital (Django, IA, DevOps) — cobrados de forma mais conceitual/superficial por serem novidade no programa." },
];

const ORDEM_ATAQUE = [
  { ordem: 1, titulo: "Português + Raciocínio Lógico", nota: "Base rápida, alto retorno" },
  { ordem: 2, titulo: "Informática", nota: "Curto, resolve rápido" },
  { ordem: 3, titulo: "Legislação do CRA-PR e CFA", nota: "Decoreba — comece cedo, repetição espaçada" },
  { ordem: 4, titulo: "Conhecimentos de Adm. Pública", nota: "Mistura teoria + lei seca" },
  { ordem: 5, titulo: "Conhecimentos do Cargo — itens 1 a 23", nota: "136 subtópicos do edital — priorize SO, arquitetura e estrutura de dados" },
];

const DISTRIBUICAO = [
  { id: "portugues", nome: "Língua Portuguesa", questoes: 10, pontos: 20 },
  { id: "rlm", nome: "Raciocínio Lógico-Matemático", questoes: 5, pontos: 10 },
  { id: "informatica", nome: "Informática", questoes: 5, pontos: 10 },
  { id: "adm", nome: "Adm. Pública e Legislação", questoes: 5, pontos: 10 },
  { id: "legis", nome: "Legislação CRA-PR / CFA", questoes: 10, pontos: 20 },
  { id: "especifico", nome: "Conhecimentos do Cargo", questoes: 15, pontos: 30 },
];

const DISCIPLINAS = [
  {
    id: "portugues",
    numero: 1,
    nome: "Língua Portuguesa",
    questoes: 10,
    descricao: "Peso alto, fácil de otimizar",
    ordemLabel: "Subtópicos do edital (Cap. 1)",
    topicos: [
      { id: "p1", ordem: 1, nome: "Fonologia: conceito", tipo: "teoria" },
      { id: "p2", ordem: 2, nome: "Encontros vocálicos", tipo: "teoria" },
      { id: "p3", ordem: 3, nome: "Dígrafos", tipo: "teoria" },
      { id: "p4", ordem: 4, nome: "Ortoépia", tipo: "teoria" },
      { id: "p5", ordem: 5, nome: "Divisão silábica", tipo: "teoria" },
      { id: "p6", ordem: 6, nome: "Prosódia", tipo: "teoria" },
      { id: "p7", ordem: 7, nome: "Acentuação", tipo: "teoria" },
      { id: "p8", ordem: 8, nome: "Ortografia", tipo: "teoria" },
      { id: "p9", ordem: 9, nome: "Morfologia: estrutura e formação das palavras", tipo: "teoria" },
      { id: "p10", ordem: 10, nome: "Classes de palavras", tipo: "teoria" },
      { id: "p11", ordem: 11, nome: "Sintaxe: termos da oração", tipo: "teoria" },
      { id: "p12", ordem: 12, nome: "Período composto", tipo: "teoria" },
      { id: "p13", ordem: 13, nome: "Conceito e classificação das orações", tipo: "revisao" },
      { id: "p14", ordem: 14, nome: "Concordância verbal e nominal", tipo: "exercicio" },
      { id: "p15", ordem: 15, nome: "Regência verbal e nominal", tipo: "exercicio" },
      { id: "p16", ordem: 16, nome: "Crase e pontuação", tipo: "exercicio" },
      { id: "p17", ordem: 17, nome: "Semântica: a significação das palavras no texto", tipo: "teoria" },
      { id: "p18", ordem: 18, nome: "Interpretação de texto", tipo: "exercicio" },
    ],
  },
  {
    id: "rlm",
    numero: 2,
    nome: "Raciocínio Lógico-Matemático",
    questoes: 5,
    ordemLabel: "Subtópicos do edital (Cap. 2)",
    topicos: [
      { id: "r1", ordem: 1, nome: "Princípio da Regressão ou Reversão", tipo: "exercicio" },
      { id: "r2", ordem: 2, nome: "Lógica dedutiva, argumentativa e quantitativa", tipo: "teoria" },
      { id: "r3", ordem: 3, nome: "Lógica matemática qualitativa", tipo: "teoria" },
      { id: "r4", ordem: 4, nome: "Sequências lógicas (números, letras e figuras)", tipo: "exercicio" },
      { id: "r5", ordem: 5, nome: "Regra de três simples e composta", tipo: "exercicio" },
      { id: "r6", ordem: 6, nome: "Razões especiais", tipo: "exercicio" },
      { id: "r7", ordem: 7, nome: "Análise combinatória e probabilidade", tipo: "exercicio" },
      { id: "r8", ordem: 8, nome: "Progressões aritmética e geométrica", tipo: "teoria" },
      { id: "r9", ordem: 9, nome: "Conjuntos: pertinência, inclusão e igualdade; união, interseção e diferença", tipo: "teoria" },
      { id: "r10", ordem: 10, nome: "Geometria plana e espacial", tipo: "exercicio" },
      { id: "r11", ordem: 11, nome: "Trigonometria", tipo: "exercicio" },
      { id: "r12", ordem: 12, nome: "Conjuntos numéricos", tipo: "teoria" },
      { id: "r13", ordem: 13, nome: "Equações de 1º e 2º grau", tipo: "exercicio" },
      { id: "r14", ordem: 14, nome: "Matrizes, determinantes e sistemas lineares", tipo: "exercicio" },
      { id: "r15", ordem: 15, nome: "Polinômios", tipo: "teoria" },
    ],
  },
  {
    id: "informatica",
    numero: 3,
    nome: "Informática",
    questoes: 5,
    descricao: "Ganho fácil pro seu perfil de dev",
    ordemLabel: "Subtópicos do edital (Cap. 3)",
    topicos: [
      { id: "i1", ordem: 1, nome: "Conhecimentos básicos de microcomputadores PC-Hardware", tipo: "teoria" },
      { id: "i2", ordem: 2, nome: "Noções de sistemas de Windows", tipo: "teoria" },
      { id: "i3", ordem: 3, nome: "Noções do processador de texto Google Documentos", nota: "Não é Office — foco no Google Workspace", tipo: "exercicio" },
      { id: "i4", ordem: 4, nome: "Noções da planilha de cálculo Google Planilhas", tipo: "exercicio" },
      { id: "i5", ordem: 5, nome: "Conceitos gerais de equipamentos e operacionalização", tipo: "teoria" },
      { id: "i6", ordem: 6, nome: "Conceitos básicos de Internet", tipo: "teoria" },
      { id: "i7", ordem: 7, nome: "Ferramentas de reunião (MS Teams, Google Meet, Zoom)", tipo: "teoria" },
    ],
  },
  {
    id: "adm",
    numero: 4,
    nome: "Conhecimentos de Administração Pública e Legislação Correlata",
    questoes: 5,
    ordemLabel: "Subtópicos do edital (Cap. 4)",
    topicos: [
      { id: "a1", ordem: 1, nome: "Direito Constitucional — Direitos e garantias fundamentais (individuais e coletivos)", tipo: "lei" },
      { id: "a2", ordem: 2, nome: "Direito Constitucional — Disposições do Art. 37 da CRFB/88", tipo: "lei" },
      { id: "a3", ordem: 3, nome: "Lei de Acesso à Informação (Lei Federal nº 12.527/2011)", tipo: "lei" },
      { id: "a4", ordem: 4, nome: "LGPD (Lei Federal nº 13.709/2018)", tipo: "lei" },
      { id: "a5", ordem: 5, nome: "Lei de Improbidade Administrativa (Lei Federal nº 8.429/1992)", tipo: "lei" },
      { id: "a6", ordem: 6, nome: "Centralização", tipo: "teoria" },
      { id: "a7", ordem: 7, nome: "Descentralização", tipo: "teoria" },
      { id: "a8", ordem: 8, nome: "Concentração", tipo: "teoria" },
      { id: "a9", ordem: 9, nome: "Desconcentração", tipo: "teoria" },
      { id: "a10", ordem: 10, nome: "Administração direta", tipo: "teoria" },
      { id: "a11", ordem: 11, nome: "Administração indireta", tipo: "teoria" },
      { id: "a12", ordem: 12, nome: "Autarquias", tipo: "teoria" },
      { id: "a13", ordem: 13, nome: "Fundações", tipo: "teoria" },
      { id: "a14", ordem: 14, nome: "Empresas públicas", tipo: "teoria" },
      { id: "a15", ordem: 15, nome: "Sociedades de economia mista", tipo: "teoria" },
      { id: "a16", ordem: 16, nome: "Ato administrativo (conceito, requisitos, atributos, classificação e espécies)", tipo: "teoria" },
      { id: "a17", ordem: 17, nome: "Agentes públicos", tipo: "teoria" },
      { id: "a18", ordem: 18, nome: "Legislação pertinente", tipo: "teoria" },
      { id: "a19", ordem: 19, nome: "Disposições constitucionais aplicáveis", tipo: "lei" },
      { id: "a20", ordem: 20, nome: "Disposições doutrinárias", tipo: "teoria" },
      { id: "a21", ordem: 21, nome: "Administração Pública: conceito", tipo: "teoria" },
      { id: "a22", ordem: 22, nome: "Espécies de atos administrativos", tipo: "teoria" },
      { id: "a23", ordem: 23, nome: "Cargo público", tipo: "teoria" },
      { id: "a24", ordem: 24, nome: "Emprego público", tipo: "teoria" },
      { id: "a25", ordem: 25, nome: "Função pública", tipo: "teoria" },
      { id: "a26", ordem: 26, nome: "Poderes administrativos (hierárquico, disciplinar, regulamentar e de polícia; uso e abuso do poder)", tipo: "teoria" },
      { id: "a27", ordem: 27, nome: "Licitação (princípios, contratação direta, dispensa e inexigibilidade, modalidades, tipos, procedimento)", tipo: "lei" },
      { id: "a28", ordem: 28, nome: "Responsabilidade civil do Estado", tipo: "teoria" },
      { id: "a29", ordem: 29, nome: "Responsabilidade civil do Estado no direito brasileiro", tipo: "teoria" },
      { id: "a30", ordem: 30, nome: "Responsabilidade por ato comissivo e por omissão do Estado", tipo: "teoria" },
      { id: "a31", ordem: 31, nome: "Requisitos para demonstração da responsabilidade", tipo: "teoria" },
      { id: "a32", ordem: 32, nome: "Causas excludentes e atenuantes", tipo: "teoria" },
    ],
  },
  {
    id: "legis",
    numero: 5,
    nome: "Legislação do CRA-PR e do CFA",
    questoes: 10,
    descricao: "Puro decoreba de lei seca",
    ordemLabel: "Subtópicos do edital (Cap. 5)",
    dica: "Monte um quadro-resumo (nome da lei → o que regula → 3 artigos-chave) em vez de decorar artigo por artigo.",
    topicos: [
      { id: "l1", ordem: 1, nome: "Lei Federal nº 4.769/1965 (exercício da profissão de Administrador e constituição do CFA/CRAs)", nota: "Leia 2x, é a base de tudo", tipo: "lei" },
      { id: "l2", ordem: 2, nome: "Decreto Federal nº 61.934/1967 (regulamenta a Lei nº 4.769/1965)", tipo: "lei" },
      { id: "l3", ordem: 3, nome: "Regimento Interno do CRA-PR — Arts. 1º a 2º", tipo: "lei" },
      { id: "l4", ordem: 4, nome: "Regimento Interno do CRA-PR — Arts. 3º a 7º", tipo: "lei" },
      { id: "l5", ordem: 5, nome: "Regimento Interno do CRA-PR — Arts. 8º a 11º", tipo: "lei" },
      { id: "l6", ordem: 6, nome: "Regimento Interno do CRA-PR — Arts. 12º a 17º", tipo: "lei" },
      { id: "l7", ordem: 7, nome: "Regimento Interno do CRA-PR — Arts. 18º a 23º", tipo: "lei" },
      { id: "l8", ordem: 8, nome: "Regimento Interno do CRA-PR — Arts. 24º a 29º", tipo: "lei" },
      { id: "l9", ordem: 9, nome: "Regimento Interno do CRA-PR — Arts. 30º a 35º", tipo: "lei" },
      { id: "l10", ordem: 10, nome: "Regimento Interno do CRA-PR — Arts. 36º a 43º", tipo: "lei" },
      { id: "l11", ordem: 11, nome: "Regimento Interno do CRA-PR — Arts. 44º a 47º", tipo: "lei" },
      { id: "l12", ordem: 12, nome: "Regimento Interno do CRA-PR — Arts. 48º a 51º", tipo: "lei" },
      { id: "l13", ordem: 13, nome: "Regimento Interno do CRA-PR — Arts. 52º a 55º", tipo: "lei" },
      { id: "l14", ordem: 14, nome: "Código de Ética e Disciplina dos Profissionais de Administração (Resolução Normativa CFA nº 671/2025)", tipo: "lei" },
    ],
  },
  {
    id: "especifico",
    numero: 6,
    nome: "Conhecimentos do Cargo — Analista de Sistemas",
    questoes: 15,
    descricao: "Bloco mais pesado e mais decisivo",
    ordemLabel: "Anexo I — Conhecimentos do Cargo (itens 1 a 23)",
    blocos: [
      {
        id: "1",
        nome: "1. Arquitetura e organização de computadores",
        descricao: "Anexo I — item 1",
        topicos: [
          { id: "e1", ordem: 1, nome: "Sistemas de numeração e representação de dados", tipo: "teoria" },
          { id: "e2", ordem: 2, nome: "Aritmética e lógica computacional", tipo: "teoria" },
          { id: "e3", ordem: 3, nome: "Microprocessadores", tipo: "teoria" },
          { id: "e4", ordem: 4, nome: "Interfaces e dispositivos periféricos", tipo: "teoria" },
          { id: "e5", ordem: 5, nome: "Conceitos de interrupções", tipo: "teoria" },
          { id: "e6", ordem: 6, nome: "Estruturas de endereçamento", tipo: "teoria" },
          { id: "e7", ordem: 7, nome: "Compiladores; ligadores (link-editores) e interpretadores", tipo: "teoria" },
        ],
      },
      {
        id: "2",
        nome: "2. Sistemas operacionais",
        descricao: "Anexo I — item 2",
        topicos: [
          { id: "e8", ordem: 8, nome: "2.1 Conceitos", tipo: "teoria" },
          { id: "e9", ordem: 9, nome: "2.2 Gerenciamento de processos", tipo: "teoria" },
          { id: "e10", ordem: 10, nome: "2.3 Gerenciamento de memória", tipo: "teoria" },
          { id: "e11", ordem: 11, nome: "2.4 Memória virtual", tipo: "teoria" },
          { id: "e12", ordem: 12, nome: "2.5 Paginação; segmentação; sistema de arquivos", tipo: "teoria" },
          { id: "e13", ordem: 13, nome: "2.6 Gerenciamento de dispositivos; concorrência; esquemas de sincronização, deadlock", tipo: "teoria" },
          { id: "e14", ordem: 14, nome: "2.7 Aspectos práticos e teóricos dos sistemas operacionais Windows/Linux", tipo: "teoria" },
        ],
      },
      {
        id: "3",
        nome: "3. Algoritmos e estrutura de dados",
        descricao: "Anexo I — item 3",
        topicos: [
          { id: "e15", ordem: 15, nome: "3.1 Noções de complexidade de algoritmo", tipo: "exercicio" },
          { id: "e16", ordem: 16, nome: "3.2 Vetores e matrizes", tipo: "exercicio" },
          { id: "e17", ordem: 17, nome: "3.3 Listas encadeadas", tipo: "teoria" },
          { id: "e18", ordem: 18, nome: "3.4 Pilhas", tipo: "teoria" },
          { id: "e19", ordem: 19, nome: "3.5 Estruturas em árvores", tipo: "teoria" },
          { id: "e20", ordem: 20, nome: "3.6 Árvores balanceadas", tipo: "teoria" },
          { id: "e21", ordem: 21, nome: "3.7 B-trees", tipo: "exercicio" },
          { id: "e22", ordem: 22, nome: "3.8 Grafos", tipo: "exercicio" },
          { id: "e23", ordem: 23, nome: "3.9 Métodos de ordenação, pesquisa e hashing", tipo: "exercicio" },
          { id: "e24", ordem: 24, nome: "3.10 Métodos de acesso a arquivos, listas invertidas", tipo: "teoria" },
        ],
      },
      {
        id: "4",
        nome: "4. Conceitos de linguagens de programação",
        descricao: "Anexo I — item 4",
        topicos: [
          { id: "e25", ordem: 25, nome: "4.1 Abstrações de dados", tipo: "teoria" },
          { id: "e26", ordem: 26, nome: "4.2 Abstrações de controle", tipo: "teoria" },
          { id: "e27", ordem: 27, nome: "4.3 Passagem de parâmetros por referência e valor", tipo: "teoria" },
          { id: "e28", ordem: 28, nome: "4.4 Escopo de variáveis", tipo: "teoria" },
          { id: "e29", ordem: 29, nome: "4.5 Tipos de dados", tipo: "teoria" },
          { id: "e30", ordem: 30, nome: "4.5.1 Vinculação", tipo: "teoria" },
          { id: "e31", ordem: 31, nome: "4.5.2 Verificação de tipos", tipo: "teoria" },
          { id: "e32", ordem: 32, nome: "4.5.3 Tipificação forte", tipo: "teoria" },
          { id: "e33", ordem: 33, nome: "4.6 Programação orientada a objetos", tipo: "teoria" },
          { id: "e34", ordem: 34, nome: "4.7 Conceitos de orientação por objetos, herança, polimorfismo, propriedades, métodos", tipo: "teoria" },
          { id: "e35", ordem: 35, nome: "4.8 Programação orientada a eventos", tipo: "teoria" },
          { id: "e36", ordem: 36, nome: "4.9 Tratamento de exceções", tipo: "teoria" },
        ],
      },
      {
        id: "5",
        nome: "5. Redes de computadores",
        descricao: "Tecnologia da Computação — item 5",
        topicos: [
          { id: "e37", ordem: 37, nome: "5.1 Conceitos, topologias e componentes", tipo: "teoria" },
          { id: "e38", ordem: 38, nome: "5.2 Comunicação de dados; meios de transmissão; serviços de comunicação", tipo: "teoria" },
          { id: "e39", ordem: 39, nome: "5.3 Redes locais e de longa distância", tipo: "teoria" },
          { id: "e40", ordem: 40, nome: "5.4 Arquitetura ISO/OSI", tipo: "teoria" },
          { id: "e41", ordem: 41, nome: "5.5 Pilha de protocolos TCP/IP", tipo: "teoria" },
          { id: "e42", ordem: 42, nome: "5.6 Serviços e protocolos: email, HTTP, SNMP, SMTP, DHCP, Proxy, LDAP, DNS", tipo: "teoria" },
          { id: "e43", ordem: 43, nome: "5.7 Repetidores, hubs, switches, roteadores, gateways", tipo: "teoria" },
          { id: "e44", ordem: 44, nome: "5.8 Segurança, tipos de ataque, firewall, DMZ", tipo: "teoria" },
          { id: "e45", ordem: 45, nome: "5.9 Padrões W3C", tipo: "teoria" },
          { id: "e46", ordem: 46, nome: "5.10 Redes sem fio", tipo: "teoria" },
          { id: "e47", ordem: 47, nome: "5.11 VPN", tipo: "teoria" },
          { id: "e48", ordem: 48, nome: "5.12 Gerência de rede", tipo: "teoria" },
        ],
      },
      {
        id: "6",
        nome: "6. Banco de dados",
        descricao: "Anexo I — item 6",
        topicos: [
          { id: "e49", ordem: 49, nome: "6.1 Conceitos e princípios", tipo: "teoria" },
          { id: "e50", ordem: 50, nome: "6.2 Administração de dados", tipo: "teoria" },
          { id: "e51", ordem: 51, nome: "6.3 Independência de dados", tipo: "teoria" },
          { id: "e52", ordem: 52, nome: "6.4 Dicionário de dados", tipo: "teoria" },
          { id: "e53", ordem: 53, nome: "6.5 Níveis da arquitetura de banco de dados", tipo: "teoria" },
          { id: "e54", ordem: 54, nome: "6.6 Modelo relacional", tipo: "teoria" },
          { id: "e55", ordem: 55, nome: "6.7 Álgebra relacional", tipo: "teoria" },
          { id: "e56", ordem: 56, nome: "6.8 Bancos de dados relacionais", tipo: "teoria" },
          { id: "e57", ordem: 57, nome: "6.9 Modelagem de dados", tipo: "teoria" },
          { id: "e58", ordem: 58, nome: "6.10 Normalização", tipo: "teoria" },
          { id: "e59", ordem: 59, nome: "6.11 Modelo entidade-relacionamento", tipo: "teoria" },
          { id: "e60", ordem: 60, nome: "6.12 Mapeamento do modelo entidade-relacionamento para o modelo relacional", tipo: "teoria" },
          { id: "e61", ordem: 61, nome: "6.13 SQL (ANSI): definição, consulta e manipulação de dados", tipo: "exercicio" },
          { id: "e62", ordem: 62, nome: "6.14 Transact-SQL", tipo: "exercicio" },
          { id: "e63", ordem: 63, nome: "6.15 Sistemas de suporte à inteligência de negócio", tipo: "teoria" },
        ],
      },
      {
        id: "7",
        nome: "7. Sistemas de gerência de banco de dados (SGBD)",
        descricao: "Anexo I — item 7",
        topicos: [
          { id: "e64", ordem: 64, nome: "7.1 Segurança", tipo: "teoria" },
          { id: "e65", ordem: 65, nome: "7.2 Conceito de transação", tipo: "teoria" },
          { id: "e66", ordem: 66, nome: "7.3 Concorrência", tipo: "teoria" },
          { id: "e67", ordem: 67, nome: "7.4 Recuperação", tipo: "teoria" },
          { id: "e68", ordem: 68, nome: "7.5 Integridade", tipo: "teoria" },
          { id: "e69", ordem: 69, nome: "7.6 Procedimentos armazenados (Stored Procedures)", tipo: "teoria" },
          { id: "e70", ordem: 70, nome: "7.7 Visões (views)", tipo: "teoria" },
          { id: "e71", ordem: 71, nome: "7.8 Gatilhos (Triggers)", tipo: "teoria" },
          { id: "e72", ordem: 72, nome: "7.9 Índices e otimização de acesso", tipo: "teoria" },
          { id: "e73", ordem: 73, nome: "7.10 Transações distribuídas", tipo: "teoria" },
        ],
      },
      {
        id: "8",
        nome: "8. Sistemas gerenciadores de banco de dados",
        descricao: "Anexo I — item 8",
        topicos: [
          { id: "e74", ordem: 74, nome: "SqlServer", tipo: "exercicio" },
          { id: "e75", ordem: 75, nome: "MySQL", tipo: "exercicio" },
          { id: "e76", ordem: 76, nome: "PostgreSQL", tipo: "exercicio" },
        ],
      },
      {
        id: "9",
        nome: "9. Integração de sistemas",
        descricao: "Anexo I — item 9",
        topicos: [
          { id: "e77", ordem: 77, nome: "Linguagem XML", tipo: "teoria" },
          { id: "e78", ordem: 78, nome: "Web Services, WSDL, UDDI, SOAP", tipo: "teoria" },
          { id: "e79", ordem: 79, nome: "RESTful Web Services", tipo: "teoria" },
        ],
      },
      {
        id: "10",
        nome: "10. Cloud Computing",
        descricao: "Fundamentos — item 10",
        topicos: [
          { id: "e80", ordem: 80, nome: "Cloud Computing (Fundamentos)", tipo: "teoria" },
        ],
      },
      {
        id: "11",
        nome: "11. Cópia de segurança (Backup)",
        descricao: "Anexo I — item 11",
        topicos: [
          { id: "e81", ordem: 81, nome: "Conceito e tipos de cópia de segurança (Backup)", tipo: "teoria" },
        ],
      },
      {
        id: "12",
        nome: "12. Inteligência artificial",
        descricao: "Anexo I — item 12",
        topicos: [
          { id: "e82", ordem: 82, nome: "Inteligência artificial (Fundamentos)", tipo: "teoria" },
          { id: "e83", ordem: 83, nome: "IA generativa e ferramentas", tipo: "teoria" },
          { id: "e84", ordem: 84, nome: "Governança e Ética", tipo: "teoria" },
        ],
      },
      {
        id: "13",
        nome: "13. Análise e projeto orientado a objetos (UML)",
        descricao: "Anexo I — item 13",
        topicos: [
          { id: "e85", ordem: 85, nome: "Conceitos de UML", tipo: "teoria" },
          { id: "e86", ordem: 86, nome: "Diagramas de casos de uso", tipo: "teoria" },
          { id: "e87", ordem: 87, nome: "Diagrama de classes/objetos", tipo: "teoria" },
          { id: "e88", ordem: 88, nome: "Diagrama de estados", tipo: "teoria" },
          { id: "e89", ordem: 89, nome: "Diagrama de colaboração/comunicação", tipo: "teoria" },
          { id: "e90", ordem: 90, nome: "Diagrama de sequência", tipo: "teoria" },
          { id: "e91", ordem: 91, nome: "Diagrama de atividades", tipo: "teoria" },
          { id: "e92", ordem: 92, nome: "Diagrama de componentes", tipo: "teoria" },
          { id: "e93", ordem: 93, nome: "Diagrama de implementação", tipo: "teoria" },
        ],
      },
      {
        id: "14",
        nome: "14. Ferramentas de suporte à análise, projeto e codificação OOP",
        descricao: "Anexo I — item 14",
        topicos: [
          { id: "e94", ordem: 94, nome: "Uso e conceitos de ferramentas de suporte à análise, projeto e codificação orientadas a objetos", tipo: "teoria" },
        ],
      },
      {
        id: "15",
        nome: "15. Engenharia de software",
        descricao: "Anexo I — item 15",
        topicos: [
          { id: "e95", ordem: 95, nome: "15.1 Ciclos de vida: cascata, espiral, orientado a reuso, prototipação, RAD, evolutivo, incremental", tipo: "teoria" },
          { id: "e96", ordem: 96, nome: "15.2 Processos de desenvolvimento — fases: concepção, elaboração, construção e transição", tipo: "teoria" },
        ],
      },
      {
        id: "16",
        nome: "16. Gerenciamento de projetos",
        descricao: "Anexo I — item 16",
        topicos: [
          { id: "e97", ordem: 97, nome: "16.1 Conceitos, planejamento, acompanhamento e controle", tipo: "teoria" },
          { id: "e98", ordem: 98, nome: "16.2 Principais áreas do gerenciamento de projetos", tipo: "teoria" },
          { id: "e99", ordem: 99, nome: "16.3 Fases de projeto", tipo: "teoria" },
          { id: "e100", ordem: 100, nome: "16.4 Gerência de escopo", tipo: "teoria" },
          { id: "e101", ordem: 101, nome: "16.5 Estrutura de decomposição de trabalho (WBS)", tipo: "teoria" },
          { id: "e102", ordem: 102, nome: "16.6 Gerência de tempo", tipo: "teoria" },
          { id: "e103", ordem: 103, nome: "16.7 Gerência de custos", tipo: "teoria" },
          { id: "e104", ordem: 104, nome: "16.8 Gerência de qualidade", tipo: "teoria" },
          { id: "e105", ordem: 105, nome: "16.9 Gerência de recursos humanos", tipo: "teoria" },
          { id: "e106", ordem: 106, nome: "16.10 Gerência de comunicação", tipo: "teoria" },
          { id: "e107", ordem: 107, nome: "16.11 Gerência de risco", tipo: "teoria" },
          { id: "e108", ordem: 108, nome: "16.12 Gerência de compras e subcontratação", tipo: "teoria" },
          { id: "e109", ordem: 109, nome: "16.13 Gerência de integração", tipo: "teoria" },
          { id: "e110", ordem: 110, nome: "16.14 PMBOK (Project Management Body of Knowledge)", tipo: "teoria" },
        ],
      },
      {
        id: "17",
        nome: "17. Gestão e recursos informacionais",
        descricao: "Anexo I — item 17",
        topicos: [
          { id: "e111", ordem: 111, nome: "17.1 Sistemas de gerenciamento de documento (GED)", tipo: "teoria" },
          { id: "e112", ordem: 112, nome: "17.2 Automação de processo de trabalho (Workflow)", tipo: "teoria" },
          { id: "e113", ordem: 113, nome: "17.3 Gerenciamento de processos de negócio (BPM)", tipo: "teoria" },
          { id: "e114", ordem: 114, nome: "17.4 Sistemas integrados de gestão (ERP)", tipo: "teoria" },
          { id: "e115", ordem: 115, nome: "17.5 CRM — Customer Relationship Management", tipo: "teoria" },
          { id: "e116", ordem: 116, nome: "17.6 Modelos de Governança em TI — ITIL", tipo: "teoria" },
          { id: "e117", ordem: 117, nome: "17.7 Modelos de Auditoria — COBIT", tipo: "teoria" },
        ],
      },
      {
        id: "18",
        nome: "18. Desenvolvimento Web",
        descricao: "Anexo I — item 18",
        topicos: [
          { id: "e118", ordem: 118, nome: "18.1 Fundamentos da Web", tipo: "teoria" },
          { id: "e119", ordem: 119, nome: "18.2 Desenvolvimento Front-end", tipo: "teoria" },
          { id: "e120", ordem: 120, nome: "18.3 Desenvolvimento Back-end", tipo: "teoria" },
          { id: "e121", ordem: 121, nome: "18.4 APIs e Integração", tipo: "teoria" },
        ],
      },
      {
        id: "19",
        nome: "19. Frameworks de Desenvolvimento",
        descricao: "Anexo I — item 19",
        topicos: [
          { id: "e122", ordem: 122, nome: "19.1 Frameworks Python", tipo: "teoria" },
        ],
      },
      {
        id: "20",
        nome: "20. Desenvolvimento com Django",
        descricao: "Anexo I — item 20",
        topicos: [
          { id: "e123", ordem: 123, nome: "20.1 Fundamentos", tipo: "teoria" },
          { id: "e124", ordem: 124, nome: "20.2 Modelagem de Dados", tipo: "teoria" },
          { id: "e125", ordem: 125, nome: "20.3 Camada de Apresentação", tipo: "teoria" },
          { id: "e126", ordem: 126, nome: "20.4 Camada de Controle", tipo: "teoria" },
          { id: "e127", ordem: 127, nome: "20.5 Administração e Segurança", tipo: "teoria" },
          { id: "e128", ordem: 128, nome: "20.6 APIs com Django", tipo: "teoria" },
          { id: "e129", ordem: 129, nome: "20.7 Testes", tipo: "teoria" },
          { id: "e130", ordem: 130, nome: "20.8 Deploy e Produção", tipo: "teoria" },
        ],
      },
      {
        id: "21",
        nome: "21. DevOps e Ferramentas de Desenvolvimento",
        descricao: "Anexo I — item 21",
        topicos: [
          { id: "e131", ordem: 131, nome: "21.1 Controle de Versão", tipo: "teoria" },
          { id: "e132", ordem: 132, nome: "21.2 Containers", tipo: "teoria" },
        ],
      },
      {
        id: "22",
        nome: "22. Licitações e contratos administrativos",
        descricao: "Anexo I — item 22",
        topicos: [
          { id: "e133", ordem: 133, nome: "22.1 Lei 14.133/21", tipo: "lei" },
          { id: "e134", ordem: 134, nome: "22.2 Instrução Normativa SGD/ME 94/22", tipo: "teoria" },
          { id: "e135", ordem: 135, nome: "22.3 Artefatos do planejamento de contratações públicas", tipo: "teoria" },
        ],
      },
      {
        id: "23",
        nome: "23. Noções de Inglês técnico",
        descricao: "Anexo I — item 23",
        topicos: [
          { id: "e136", ordem: 136, nome: "Noções de Inglês técnico", tipo: "revisao" },
        ],
      }
    ],
    topicos: [],
  },
];

// Flatten blocos into topicos for especifico
(function () {
  const esp = DISCIPLINAS.find((d) => d.id === "especifico");
  if (esp && esp.blocos) {
    esp.topicos = esp.blocos.flatMap((b) => b.topicos);
  }
})();
