const EXAM_DATE = new Date(2026, 8, 13);

const INTRO = {
  base: "Baseado no Anexo I do Edital nº 1/2026 + perfil histórico da banca Consulplan.",
};

const PERFIL_BANCA = [
  { area: "Direito / Legislação", texto: "Cobrança <strong>literal da letra de lei</strong>, raramente doutrina ou jurisprudência pesada." },
  { area: "Português", texto: "Interpretação de texto é o carro-chefe, seguido de sintaxe/morfologia." },
  { area: "Raciocínio Lógico", texto: "Resolvido em boa parte com fórmulas diretas — decoreba de fórmula rende muito." },
  { area: "Informática", texto: "Foco em <strong>Windows</strong> e pacote de escritório, não costuma ser complexa." },
  { area: "Cargo (TI)", texto: "Mistura teoria clássica (SO, redes, BD) com tópicos novos do edital (Django, IA, DevOps) — cobrados de forma mais conceitual/superficial por serem novidade no programa." },
];

const ORDEM_ATAQUE = [
  { ordem: 1, titulo: "Português + Raciocínio Lógico", nota: "Base rápida, alto retorno" },
  { ordem: 2, titulo: "Informática", nota: "Curto, resolve rápido" },
  { ordem: 3, titulo: "Legislação do CRA-PR e CFA", nota: "Decoreba — comece cedo, repetição espaçada" },
  { ordem: 4, titulo: "Conhecimentos de Adm. Pública", nota: "Mistura teoria + lei seca" },
  { ordem: 5, titulo: "Conhecimentos do Cargo — Bloco A → B → C", nota: "SO, arquitetura e estrutura de dados por último" },
];

const DISTRIBUICAO = [
  { id: "portugues", nome: "Língua Portuguesa", questoes: 10, pontos: 20 },
  { id: "rlm", nome: "Raciocínio Lógico-Matemático", questoes: 5, pontos: 10 },
  { id: "informatica", nome: "Informática", questoes: 5, pontos: 10 },
  { id: "adm", nome: "Adm. Pública e Legislação", questoes: 5, pontos: 10 },
  { id: "legis", nome: "Legislação CRA-PR / CFA", questoes: 10, pontos: 20 },
  { id: "especifico", nome: "Conhecimentos do Cargo", questoes: 15, pontos: 30 },
];

const DISCIPLINAS = [
  {
    id: "portugues",
    numero: 1,
    nome: "Língua Portuguesa",
    questoes: 10,
    descricao: "Peso alto, fácil de otimizar",
    ordemLabel: "Subtópicos do edital (Cap. 1)",
    topicos: [
      { id: "p1", ordem: 1, nome: "Fonologia: conceito", tipo: "teoria" },
      { id: "p2", ordem: 2, nome: "Encontros vocálicos", tipo: "teoria" },
      { id: "p3", ordem: 3, nome: "Dígrafos", tipo: "teoria" },
      { id: "p4", ordem: 4, nome: "Ortoépia", tipo: "teoria" },
      { id: "p5", ordem: 5, nome: "Divisão silábica", tipo: "teoria" },
      { id: "p6", ordem: 6, nome: "Prosódia", tipo: "teoria" },
      { id: "p7", ordem: 7, nome: "Acentuação", tipo: "teoria" },
      { id: "p8", ordem: 8, nome: "Ortografia", tipo: "teoria" },
      { id: "p9", ordem: 9, nome: "Morfologia: estrutura e formação das palavras", tipo: "teoria" },
      { id: "p10", ordem: 10, nome: "Classes de palavras", tipo: "teoria" },
      { id: "p11", ordem: 11, nome: "Sintaxe: termos da oração", tipo: "teoria" },
      { id: "p12", ordem: 12, nome: "Período composto", tipo: "teoria" },
      { id: "p13", ordem: 13, nome: "Conceito e classificação das orações", tipo: "revisao" },
      { id: "p14", ordem: 14, nome: "Concordância verbal e nominal", tipo: "exercicio" },
      { id: "p15", ordem: 15, nome: "Regência verbal e nominal", tipo: "exercicio" },
      { id: "p16", ordem: 16, nome: "Crase e pontuação", tipo: "exercicio" },
      { id: "p17", ordem: 17, nome: "Semântica: a significação das palavras no texto", tipo: "teoria" },
      { id: "p18", ordem: 18, nome: "Interpretação de texto", tipo: "exercicio" },
    ],
  },
  {
    id: "rlm",
    numero: 2,
    nome: "Raciocínio Lógico-Matemático",
    questoes: 5,
    ordemLabel: "Subtópicos do edital (Cap. 2)",
    topicos: [
      { id: "r1", ordem: 1, nome: "Princípio da Regressão ou Reversão", tipo: "exercicio" },
      { id: "r2", ordem: 2, nome: "Lógica dedutiva, argumentativa e quantitativa", tipo: "teoria" },
      { id: "r3", ordem: 3, nome: "Lógica matemática qualitativa", tipo: "teoria" },
      { id: "r4", ordem: 4, nome: "Sequências lógicas (números, letras e figuras)", tipo: "exercicio" },
      { id: "r5", ordem: 5, nome: "Regra de três simples e composta", tipo: "exercicio" },
      { id: "r6", ordem: 6, nome: "Razões especiais", tipo: "exercicio" },
      { id: "r7", ordem: 7, nome: "Análise combinatória e probabilidade", tipo: "exercicio" },
      { id: "r8", ordem: 8, nome: "Progressões aritmética e geométrica", tipo: "teoria" },
      { id: "r9", ordem: 9, nome: "Conjuntos: pertinência, inclusão e igualdade; união, interseção e diferença", tipo: "teoria" },
      { id: "r10", ordem: 10, nome: "Geometria plana e espacial", tipo: "exercicio" },
      { id: "r11", ordem: 11, nome: "Trigonometria", tipo: "exercicio" },
      { id: "r12", ordem: 12, nome: "Conjuntos numéricos", tipo: "teoria" },
      { id: "r13", ordem: 13, nome: "Equações de 1º e 2º grau", tipo: "exercicio" },
      { id: "r14", ordem: 14, nome: "Matrizes, determinantes e sistemas lineares", tipo: "exercicio" },
      { id: "r15", ordem: 15, nome: "Polinômios", tipo: "teoria" },
    ],
  },
  {
    id: "informatica",
    numero: 3,
    nome: "Informática",
    questoes: 5,
    descricao: "Ganho fácil pro seu perfil de dev",
    ordemLabel: "Subtópicos do edital (Cap. 3)",
    topicos: [
      { id: "i1", ordem: 1, nome: "Conhecimentos básicos de microcomputadores PC-Hardware", tipo: "teoria" },
      { id: "i2", ordem: 2, nome: "Noções de sistemas de Windows", tipo: "teoria" },
      { id: "i3", ordem: 3, nome: "Noções do processador de texto Google Documentos", nota: "Não é Office — foco no Google Workspace", tipo: "exercicio" },
      { id: "i4", ordem: 4, nome: "Noções da planilha de cálculo Google Planilhas", tipo: "exercicio" },
      { id: "i5", ordem: 5, nome: "Conceitos gerais de equipamentos e operacionalização", tipo: "teoria" },
      { id: "i6", ordem: 6, nome: "Conceitos básicos de Internet", tipo: "teoria" },
      { id: "i7", ordem: 7, nome: "Ferramentas de reunião (MS Teams, Google Meet, Zoom)", tipo: "teoria" },
    ],
  },
  {
    id: "adm",
    numero: 4,
    nome: "Conhecimentos de Administração Pública e Legislação Correlata",
    questoes: 5,
    ordemLabel: "Subtópicos do edital (Cap. 4)",
    topicos: [
      { id: "a1", ordem: 1, nome: "Direito Constitucional — Direitos e garantias fundamentais (individuais e coletivos)", tipo: "lei" },
      { id: "a2", ordem: 2, nome: "Direito Constitucional — Disposições do Art. 37 da CRFB/88", tipo: "lei" },
      { id: "a3", ordem: 3, nome: "Lei de Acesso à Informação (Lei Federal nº 12.527/2011)", tipo: "lei" },
      { id: "a4", ordem: 4, nome: "LGPD (Lei Federal nº 13.709/2018)", tipo: "lei" },
      { id: "a5", ordem: 5, nome: "Lei de Improbidade Administrativa (Lei Federal nº 8.429/1992)", tipo: "lei" },
      { id: "a6", ordem: 6, nome: "Centralização", tipo: "teoria" },
      { id: "a7", ordem: 7, nome: "Descentralização", tipo: "teoria" },
      { id: "a8", ordem: 8, nome: "Concentração", tipo: "teoria" },
      { id: "a9", ordem: 9, nome: "Desconcentração", tipo: "teoria" },
      { id: "a10", ordem: 10, nome: "Administração direta", tipo: "teoria" },
      { id: "a11", ordem: 11, nome: "Administração indireta", tipo: "teoria" },
      { id: "a12", ordem: 12, nome: "Autarquias", tipo: "teoria" },
      { id: "a13", ordem: 13, nome: "Fundações", tipo: "teoria" },
      { id: "a14", ordem: 14, nome: "Empresas públicas", tipo: "teoria" },
      { id: "a15", ordem: 15, nome: "Sociedades de economia mista", tipo: "teoria" },
      { id: "a16", ordem: 16, nome: "Ato administrativo (conceito, requisitos, atributos, classificação e espécies)", tipo: "teoria" },
      { id: "a17", ordem: 17, nome: "Agentes públicos", tipo: "teoria" },
      { id: "a18", ordem: 18, nome: "Legislação pertinente", tipo: "teoria" },
      { id: "a19", ordem: 19, nome: "Disposições constitucionais aplicáveis", tipo: "lei" },
      { id: "a20", ordem: 20, nome: "Disposições doutrinárias", tipo: "teoria" },
      { id: "a21", ordem: 21, nome: "Administração Pública: conceito", tipo: "teoria" },
      { id: "a22", ordem: 22, nome: "Espécies de atos administrativos", tipo: "teoria" },
      { id: "a23", ordem: 23, nome: "Cargo público", tipo: "teoria" },
      { id: "a24", ordem: 24, nome: "Emprego público", tipo: "teoria" },
      { id: "a25", ordem: 25, nome: "Função pública", tipo: "teoria" },
      { id: "a26", ordem: 26, nome: "Poderes administrativos (hierárquico, disciplinar, regulamentar e de polícia; uso e abuso do poder)", tipo: "teoria" },
      { id: "a27", ordem: 27, nome: "Licitação (princípios, contratação direta, dispensa e inexigibilidade, modalidades, tipos, procedimento)", tipo: "lei" },
      { id: "a28", ordem: 28, nome: "Responsabilidade civil do Estado", tipo: "teoria" },
      { id: "a29", ordem: 29, nome: "Responsabilidade civil do Estado no direito brasileiro", tipo: "teoria" },
      { id: "a30", ordem: 30, nome: "Responsabilidade por ato comissivo e por omissão do Estado", tipo: "teoria" },
      { id: "a31", ordem: 31, nome: "Requisitos para demonstração da responsabilidade", tipo: "teoria" },
      { id: "a32", ordem: 32, nome: "Causas excludentes e atenuantes", tipo: "teoria" },
    ],
  },
  {
    id: "legis",
    numero: 5,
    nome: "Legislação do CRA-PR e do CFA",
    questoes: 10,
    descricao: "Puro decoreba de lei seca",
    ordemLabel: "Subtópicos do edital (Cap. 5)",
    dica: "Monte um quadro-resumo (nome da lei → o que regula → 3 artigos-chave) em vez de decorar artigo por artigo.",
    topicos: [
      { id: "l1", ordem: 1, nome: "Lei Federal nº 4.769/1965 (exercício da profissão de Administrador e constituição do CFA/CRAs)", nota: "Leia 2x, é a base de tudo", tipo: "lei" },
      { id: "l2", ordem: 2, nome: "Decreto Federal nº 61.934/1967 (regulamenta a Lei nº 4.769/1965)", tipo: "lei" },
      { id: "l3", ordem: 3, nome: "Regimento Interno do CRA-PR — Arts. 1º a 2º", tipo: "lei" },
      { id: "l4", ordem: 4, nome: "Regimento Interno do CRA-PR — Arts. 3º a 7º", tipo: "lei" },
      { id: "l5", ordem: 5, nome: "Regimento Interno do CRA-PR — Arts. 8º a 11º", tipo: "lei" },
      { id: "l6", ordem: 6, nome: "Regimento Interno do CRA-PR — Arts. 12º a 17º", tipo: "lei" },
      { id: "l7", ordem: 7, nome: "Regimento Interno do CRA-PR — Arts. 18º a 23º", tipo: "lei" },
      { id: "l8", ordem: 8, nome: "Regimento Interno do CRA-PR — Arts. 24º a 29º", tipo: "lei" },
      { id: "l9", ordem: 9, nome: "Regimento Interno do CRA-PR — Arts. 30º a 35º", tipo: "lei" },
      { id: "l10", ordem: 10, nome: "Regimento Interno do CRA-PR — Arts. 36º a 43º", tipo: "lei" },
      { id: "l11", ordem: 11, nome: "Regimento Interno do CRA-PR — Arts. 44º a 47º", tipo: "lei" },
      { id: "l12", ordem: 12, nome: "Regimento Interno do CRA-PR — Arts. 48º a 51º", tipo: "lei" },
      { id: "l13", ordem: 13, nome: "Regimento Interno do CRA-PR — Arts. 52º a 55º", tipo: "lei" },
      { id: "l14", ordem: 14, nome: "Código de Ética e Disciplina (Resolução Normativa CFA nº 640/2024)", tipo: "lei" },
    ],
  },
  {
    id: "especifico",
    numero: 6,
    nome: "Conhecimentos do Cargo — Analista de Sistemas",
    questoes: 15,
    descricao: "Bloco mais pesado e mais decisivo",
    ordemLabel: "Reorganizado em blocos temáticos (fácil → difícil)",
    notaFinal: "Com histórico em JS/front-end, o Bloco A já dá vantagem real. Foco maior de tempo: Legislação CRA-PR/CFA e Bloco C (SO, arquitetura, estrutura de dados).",
    blocos: [
      {
        id: "A",
        nome: "Bloco A — Mais fácil pra você",
        descricao: "Aproveite a familiaridade (front-end/JS)",
        topicos: [
          { id: "e1", ordem: 1, nome: "Desenvolvimento Web (fundamentos, front-end, back-end, APIs)", tipo: "teoria" },
          { id: "e2", ordem: 2, nome: "Frameworks Python / Django (modelagem, views, admin, APIs, testes, deploy)", tipo: "teoria" },
          { id: "e3", ordem: 3, nome: "DevOps — Controle de versão (Git) e Containers (conceitos)", tipo: "teoria" },
          { id: "e4", ordem: 4, nome: "Engenharia de software — ciclos de vida (cascata, espiral, RAD, incremental) e fases", tipo: "teoria" },
        ],
      },
      {
        id: "B",
        nome: "Bloco B — Intermediário",
        descricao: "Teoria estruturada, exige memorização organizada",
        topicos: [
          { id: "e5", ordem: 5, nome: "Banco de dados — conceitos, modelo relacional, modelagem ER, normalização", tipo: "teoria" },
          { id: "e6", ordem: 6, nome: "SQL (ANSI) e Transact-SQL — definição, consulta, manipulação", tipo: "exercicio" },
          { id: "e7", ordem: 7, nome: "SGBD — transação, concorrência, backup, views, triggers, stored procedures", tipo: "teoria" },
          { id: "e8", ordem: 8, nome: "Redes de computadores — topologias, TCP/IP, protocolos (email, DNS, DHCP etc.)", tipo: "teoria" },
          { id: "e9", ordem: 9, nome: "Segurança de redes — firewall, DMZ, VPN, tipos de ataque", tipo: "teoria" },
          { id: "e10", ordem: 10, nome: "Análise orientada a objetos com UML — casos de uso, classes, sequência, atividades", tipo: "teoria" },
          { id: "e11", ordem: 11, nome: "Gestão de projetos — PMBOK (escopo, tempo, custo, qualidade, risco, integração)", tipo: "teoria" },
        ],
      },
      {
        id: "C",
        nome: "Bloco C — Mais difícil",
        descricao: "Mais técnico-conceitual — exige mais tempo e revisão",
        topicos: [
          { id: "e12", ordem: 12, nome: "Arquitetura de computadores — numeração, aritmética computacional, microprocessadores, interrupções", tipo: "teoria" },
          { id: "e13", ordem: 13, nome: "Sistemas operacionais — processos, memória virtual, paginação, deadlock", tipo: "teoria" },
          { id: "e14", ordem: 14, nome: "Algoritmos e estrutura de dados — árvores, grafos, B-trees, hashing, complexidade", tipo: "exercicio" },
          { id: "e15", ordem: 15, nome: "Linguagens de programação — abstrações, tipificação, POO, tratamento de exceções", tipo: "teoria" },
          { id: "e16", ordem: 16, nome: "Integração de sistemas — XML, Web Services, SOAP, REST, WSDL/UDDI", tipo: "teoria" },
          { id: "e17", ordem: 17, nome: "Gestão e recursos informacionais — GED, Workflow, BPM, ERP, CRM, ITIL, COBIT", nota: "Muita sigla, pouca profundidade — decoreba de conceito-chave", tipo: "revisao" },
          { id: "e18", ordem: 18, nome: "Cloud Computing e IA generativa (fundamentos, governança/ética)", nota: "Tópico novo no edital, cobrança provavelmente conceitual", tipo: "teoria" },
          { id: "e19", ordem: 19, nome: "Licitações e contratos — Lei 14.133/21, IN SGD/ME 94/22, ETP, TR", tipo: "lei" },
          { id: "e20", ordem: 20, nome: "Inglês técnico — vocabulário de TI básico", nota: "Normalmente poucas questões", tipo: "revisao" },
        ],
      },
    ],
    topicos: [],
  },
];

// Flatten blocos into topicos for especifico
(function () {
  const esp = DISCIPLINAS.find((d) => d.id === "especifico");
  if (esp && esp.blocos) {
    esp.topicos = esp.blocos.flatMap((b) => b.topicos);
  }
})();
