/* Banco de questões — padrão Consulplan (4 alternativas) + temas CRA-PR / edital 2026 */

const PROVAS_OFICIAIS = [
  {
    titulo: "CRA-PR 2022 — Analista de Sistemas (Quadrix)",
    nota: "Prova anterior do mesmo cargo — referência de estilo para TI",
    links: [
      { label: "Prova PDF", url: "https://www.pciconcursos.com.br/provas/download/analista-de-sistemas-i-cra-pr-quadrix-2022" },
    ],
  },
  {
    titulo: "CRA-PR 2023 — Analista de Sistemas I (Quadrix)",
    nota: "Última prova aplicada para o cargo",
    links: [
      { label: "Prova + Gabarito", url: "https://www.pciconcursos.com.br/provas/download/analista-de-sistemas-i-cra-pr-quadrix-2023" },
    ],
  },
];

const QUIZ_CONFIG = {
  portugues:   { nome: "Língua Portuguesa",           padrao: 10, max: 12 },
  rlm:         { nome: "Raciocínio Lógico-Matemático", padrao: 5,  max: 8  },
  informatica: { nome: "Informática",                  padrao: 5,  max: 8  },
  adm:         { nome: "Adm. Pública e Legislação",    padrao: 5,  max: 8  },
  legis:       { nome: "Legislação CRA-PR / CFA",      padrao: 10, max: 12 },
  especifico:  { nome: "Conhecimentos do Cargo",       padrao: 15, max: 18 },
  completo:    { nome: "Simulado completo",            padrao: 50, max: 50 },
};

const QUESTOES = {
  portugues: [
    { id: "pt01", fonte: "Estilo Consulplan", enunciado: "Assinale a alternativa em que todas as palavras obedecem à nova ortografia:", alternativas: ["A) ideia, assembleia, benção", "B) ideia, assembleia, bênção", "C) idéia, assembleia, benção", "D) idéia, assembléia, bênção"], correta: 0, explicacao: "Ideia e assembleia não levam acento; benção é a forma correta." },
    { id: "pt02", fonte: "Estilo Consulplan", enunciado: 'Em "Os analistas, cujas funções exigem dedicação, foram convocados", a vírgula após "dedicação" separa:', alternativas: ["A) oração subordinada adjetiva explicativa", "B) oração subordinada adjetiva restritiva", "C) aposto explicativo", "D) adjunto adverbial deslocado"], correta: 0, explicacao: "Oração com 'cujas' entre vírgulas — adjetiva explicativa." },
    { id: "pt03", fonte: "Estilo Consulplan", enunciado: "Em relação à concordância verbal, assinale a alternativa correta:", alternativas: ["A) Fazem dois anos que trabalho aqui.", "B) Houveram muitos problemas no sistema.", "C) Devem haver soluções viáveis.", "D) Existe muitas vagas no edital."], correta: 2, explicacao: "Com auxiliar modal, 'haver' (existir) concorda com o sujeito." },
    { id: "pt04", fonte: "Estilo Consulplan", enunciado: "Assinale a frase em que o uso da crase está correto:", alternativas: ["A) Refiro-me à você.", "B) Fui à Curitiba na semana passada.", "C) Assistirei à reunião às 14h.", "D) Entreguei o relatório à ele."], correta: 2, explicacao: "Crase em 'à reunião' e 'às 14h'." },
    { id: "pt05", fonte: "Estilo Consulplan", enunciado: "Em 'A tecnologia transforma a gestão pública, porém exige capacitação', 'porém' estabelece relação de:", alternativas: ["A) adição", "B) conclusão", "C) oposição", "D) causa"], correta: 2, explicacao: "'Porém' é conjunção adversativa." },
    { id: "pt06", fonte: "Estilo Consulplan", enunciado: "Assinale a alternativa em que a regência verbal está correta:", alternativas: ["A) O gestor assistiu o relatório.", "B) O analista obedeceu ao regulamento.", "C) Precisamos acessar ao sistema.", "D) O servidor informou ao problema."], correta: 1, explicacao: "Obedecer + a: obedeceu ao regulamento." },
    { id: "pt07", fonte: "Estilo Consulplan", enunciado: "Quanto à colocação pronominal, está correta:", alternativas: ["A) Não se deve ignorar as normas.", "B) Não deve-se ignorar as normas.", "C) Não deve ignorar-se as normas.", "D) Deve não se ignorar as normas."], correta: 0, explicacao: "Com negação, próclise: 'Não se deve'." },
    { id: "pt08", fonte: "Estilo Consulplan", enunciado: "'Administração' é classificada morfologicamente como:", alternativas: ["A) substantivo abstrato", "B) substantivo concreto", "C) adjetivo", "D) advérbio"], correta: 0, explicacao: "Designa ideia/ação — substantivo abstrato." },
    { id: "pt09", fonte: "Estilo Consulplan", enunciado: "Em 'O edital que publicamos ontem já está disponível', 'que publicamos ontem' é:", alternativas: ["A) oração subordinada adjetiva restritiva", "B) oração subordinada adjetiva explicativa", "C) oração subordinada substantiva", "D) oração coordenada sindética"], correta: 0, explicacao: "Sem vírgulas — restritiva." },
    { id: "pt10", fonte: "Estilo Consulplan", enunciado: "Assinale a alternativa com erro de concordância nominal:", alternativas: ["A) Ela mesma fez a revisão.", "B) Comprei meia dúzia de ovos.", "C) É proibido entrada de menores.", "D) Ficaram anexo os documentos."], correta: 3, explicacao: "Correto: 'Ficaram anexos os documentos'." },
    { id: "pt11", fonte: "Estilo Consulplan", enunciado: "O pronome 'cujo' em 'O servidor cujo registro está irregular' indica:", alternativas: ["A) posse", "B) comparação", "C) causa", "D) tempo"], correta: 0, explicacao: "'Cujo' = de quem / a quem pertence." },
    { id: "pt12", fonte: "Estilo Consulplan", enunciado: "'Se houver dúvidas, consulte o edital' — 'houver' está no:", alternativas: ["A) futuro do pretérito", "B) futuro do presente", "C) futuro do subjuntivo", "D) pretérito imperfeito do subjuntivo"], correta: 2, explicacao: "Condição futura — futuro do subjuntivo." },
  ],
  rlm: [
    { id: "rl01", fonte: "Estilo Consulplan", enunciado: "PA: 1º termo 3, razão 4. O 10º termo é:", alternativas: ["A) 39", "B) 40", "C) 43", "D) 47"], correta: 0, explicacao: "an = 3 + 9×4 = 39." },
    { id: "rl02", fonte: "Estilo Consulplan", enunciado: "5 operadores digitam 200 formulários em 4 dias. Quantos 10 operadores digitam em 2 dias?", alternativas: ["A) 100", "B) 200", "C) 400", "D) 800"], correta: 1, explicacao: "Regra de três: 10/5 × 2/4 × 200 = 200." },
    { id: "rl03", fonte: "Estilo Consulplan", enunciado: "A negação de 'Todo servidor é eficiente' é:", alternativas: ["A) Nenhum servidor é eficiente", "B) Algum servidor não é eficiente", "C) Todo servidor não é eficiente", "D) Algum servidor é eficiente"], correta: 1, explicacao: "Negação de universal afirmativa." },
    { id: "rl04", fonte: "Estilo Consulplan", enunciado: "Próximo termo: 2, 6, 18, 54, ...", alternativas: ["A) 108", "B) 162", "C) 216", "D) 72"], correta: 1, explicacao: "PG razão 3: 54×3 = 162." },
    { id: "rl05", fonte: "Estilo Consulplan", enunciado: "30 pessoas: 18 inglês, 12 espanhol, 8 ambos. Quantas não falam nenhum?", alternativas: ["A) 4", "B) 6", "C) 8", "D) 10"], correta: 2, explicacao: "|A∪B| = 22; 30-22 = 8." },
    { id: "rl06", fonte: "Estilo Consulplan", enunciado: "R$ 2.000 a juros simples 3% a.m. por 4 meses rende:", alternativas: ["A) R$ 120", "B) R$ 200", "C) R$ 240", "D) R$ 280"], correta: 2, explicacao: "J = 2000×0,03×4 = R$ 240." },
    { id: "rl07", fonte: "Estilo Consulplan", enunciado: "Probabilidade de cara em moeda honesta:", alternativas: ["A) 1/4", "B) 1/3", "C) 1/2", "D) 2/3"], correta: 2, explicacao: "Dois resultados equiprováveis." },
    { id: "rl08", fonte: "Estilo Consulplan", enunciado: "p verdadeiro e q falso. Valor de p → q:", alternativas: ["A) verdadeiro", "B) falso", "C) indeterminado", "D) contingente"], correta: 1, explicacao: "Implicação falsa só com V→F." },
  ],
  informatica: [
    { id: "if01", fonte: "Estilo Consulplan", enunciado: "No Windows, atalho que abre o Gerenciador de Tarefas diretamente:", alternativas: ["A) Ctrl+Shift+Esc", "B) Ctrl+Alt+Del", "C) Win+R", "D) Alt+F4"], correta: 0, explicacao: "Ctrl+Shift+Esc abre o Gerenciador de Tarefas." },
    { id: "if02", fonte: "Estilo Consulplan", enunciado: "No Google Sheets, fixar a primeira linha:", alternativas: ["A) Exibir → Congelar → 1 linha", "B) Formatar → Fixar célula", "C) Dados → Filtrar", "D) Inserir → Linha fixa"], correta: 0, explicacao: "Menu Exibir → Congelar." },
    { id: "if03", fonte: "Estilo Consulplan", enunciado: "Componente de entrada de dados:", alternativas: ["A) Monitor", "B) Impressora", "C) Teclado", "D) Caixa de som"], correta: 2, explicacao: "Teclado é dispositivo de entrada." },
    { id: "if04", fonte: "Estilo Consulplan", enunciado: "HTTPS usa, por padrão, a porta:", alternativas: ["A) 21", "B) 25", "C) 80", "D) 443"], correta: 3, explicacao: "HTTPS = porta 443." },
    { id: "if05", fonte: "Estilo Consulplan", enunciado: "No Teams, compartilhar só uma janela:", alternativas: ["A) Compartilhar tela inteira", "B) Compartilhar janela", "C) Apresentar ao vivo", "D) Gravar reunião"], correta: 1, explicacao: "Teams permite tela, janela ou aba." },
    { id: "if06", fonte: "Estilo Consulplan", enunciado: "Google Docs na nuvem usa principalmente:", alternativas: ["A) formato proprietário na nuvem (não .docx nativo)", "B) apenas .docx local", "C) .xlsx", "D) .ppt"], correta: 0, explicacao: "Docs é nativo na nuvem; exporta para .docx/.pdf." },
    { id: "if07", fonte: "Estilo Consulplan", enunciado: "Backup incremental salva:", alternativas: ["A) todos os arquivos sempre", "B) só arquivos alterados desde o último backup", "C) só o SO", "D) só texto"], correta: 1, explicacao: "Incremental = mudanças desde backup anterior." },
    { id: "if08", fonte: "Estilo Consulplan", enunciado: "Phishing visa:", alternativas: ["A) sobrecarregar servidores", "B) roubar credenciais por engano", "C) criptografar disco", "D) interceptar Wi-Fi"], correta: 1, explicacao: "Engenharia social para roubar dados." },
  ],
  adm: [
    { id: "ad01", fonte: "CF art. 37", enunciado: "Princípio do art. 37 da CF que NÃO está expresso:", alternativas: ["A) legalidade", "B) impessoalidade", "C) autotutela", "D) eficiência"], correta: 2, explicacao: "Art. 37: legalidade, impessoalidade, moralidade, publicidade, eficiência." },
    { id: "ad02", fonte: "LAI 12.527/11", enunciado: "Prazo padrão de resposta na LAI:", alternativas: ["A) 10 dias", "B) 15 dias", "C) 20 dias", "D) 30 dias"], correta: 2, explicacao: "20 dias + 10 de prorrogação." },
    { id: "ad03", fonte: "LGPD", enunciado: "Dados sensíveis na LGPD exigem, em regra:", alternativas: ["A) consentimento verbal", "B) base legal específica", "C) autorização do chefe", "D) publicação em DOU"], correta: 1, explicacao: "Art. 11 — hipóteses taxativas." },
    { id: "ad04", fonte: "Estilo Consulplan", enunciado: "Autarquia é administração:", alternativas: ["A) direta", "B) indireta", "C) mista", "D) delegada"], correta: 1, explicacao: "Autarquia = indireta." },
    { id: "ad05", fonte: "Estilo Consulplan", enunciado: "Atributo que permite à Administração rever seus atos:", alternativas: ["A) presunção de legitimidade", "B) autoexecutoriedade", "C) imperatividade", "D) autotutela"], correta: 3, explicacao: "Autotutela — anular/revogar atos próprios." },
    { id: "ad06", fonte: "Lei 14.133/21", enunciado: "Pregão na Lei 14.133 é para:", alternativas: ["A) obras de engenharia", "B) bens e serviços comuns", "C) alienação de bens", "D) permissão de serviço"], correta: 1, explicacao: "Pregão — bens e serviços comuns." },
    { id: "ad07", fonte: "Estilo Consulplan", enunciado: "Poder de punir servidores:", alternativas: ["A) hierárquico", "B) disciplinar", "C) regulamentar", "D) de polícia"], correta: 1, explicacao: "Poder disciplinar." },
    { id: "ad08", fonte: "CF art. 37 §6º", enunciado: "Responsabilidade civil do Estado (regra CF):", alternativas: ["A) sempre objetiva sem exceção", "B) sempre subjetiva", "C) objetiva com nexo causal", "D) inexistente"], correta: 2, explicacao: "Teoria do risco administrativo." },
  ],
  legis: [
    { id: "lg01", fonte: "Lei 4.769/65", enunciado: "Lei 4.769/1965 instituiu:", alternativas: ["A) CFC", "B) CFA e CRAs", "C) CONFEA", "D) OAB"], correta: 1, explicacao: "Regulamenta administrador e cria CFA/CRAs." },
    { id: "lg02", fonte: "Lei 4.769/65", enunciado: "Exercício da profissão de administrador exige:", alternativas: ["A) diploma e registro no CRA", "B) só diploma", "C) exame OAB", "D) registro no MTb"], correta: 0, explicacao: "Registro no conselho regional." },
    { id: "lg03", fonte: "Lei 4.769/65", enunciado: "Compete ao CFA:", alternativas: ["A) fiscalizar só empresas privadas", "B) orientar e disciplinar a profissão nacionalmente", "C) aplicar penas criminais", "D) elaborar leis"], correta: 1, explicacao: "CFA — âmbito nacional." },
    { id: "lg04", fonte: "Decreto 61.934/67", enunciado: "Decreto 61.934/1967:", alternativas: ["A) regulamenta a Lei 4.769/65", "B) cria só o CRA-PR", "C) fixa anuidades", "D) revoga ética"], correta: 0, explicacao: "Regulamentação da lei-base." },
    { id: "lg05", fonte: "Lei 12.514/11", enunciado: "Lei 12.514/2011 trata de:", alternativas: ["A) código de ética", "B) anuidades de conselhos", "C) regimento CRA", "D) licitações"], correta: 1, explicacao: "Anuidades dos conselhos." },
    { id: "lg06", fonte: "CRA-PR", enunciado: "Regimento Interno do CRA-PR disciplina:", alternativas: ["A) organização do conselho regional", "B) código penal", "C) tributos federais", "D) contabilidade pública"], correta: 0, explicacao: "Estrutura e funcionamento do CRA-PR." },
    { id: "lg07", fonte: "Código de Ética", enunciado: "Violação do Código de Ética pode gerar:", alternativas: ["A) só advertência verbal", "B) sanções disciplinares do conselho", "C) prisão imediata", "D) demissão automática"], correta: 1, explicacao: "Processo ético-disciplinar." },
    { id: "lg08", fonte: "Lei 4.769/65", enunciado: "Consultoria e auditoria administrativa são privativas segundo:", alternativas: ["A) norma interna só", "B) Lei 4.769/65", "C) decreto municipal", "D) CLT só"], correta: 1, explicacao: "Atividades privativas na lei." },
    { id: "lg09", fonte: "Resoluções CFA", enunciado: "Melhor estratégia para Resoluções CFA em prova Consulplan:", alternativas: ["A) decorar tudo sem filtro", "B) ementa, objeto e artigos-chave", "C) ignorar recentes", "D) só jurisprudência"], correta: 1, explicacao: "Quadro-resumo por resolução." },
    { id: "lg10", fonte: "Lei 4.769/65", enunciado: "CRA tem competência para:", alternativas: ["A) fiscalizar exercício profissional na região", "B) legislar penal", "C) nomear ministros", "D) julgar crimes"], correta: 0, explicacao: "Fiscalização regional." },
    { id: "lg11", fonte: "CRA-PR", enunciado: "Registro irregular no CRA-PR:", alternativas: ["A) permite exercício normal", "B) sujeita a fiscalização e sanções", "C) isenta anuidade", "D) impede só setor privado"], correta: 1, explicacao: "Registro regular é obrigatório." },
    { id: "lg12", fonte: "CFA/CRA", enunciado: "Sistema CFA/CRA foi criado para:", alternativas: ["A) representar administradores", "B) certificar só TI", "C) regulamentar medicina", "D) fiscalizar concursos"], correta: 0, explicacao: "Profissão de administrador." },
  ],
  especifico: [
    { id: "es01", fonte: "Edital 2026 / CRA-PR TI", enunciado: "Em Django, tabelas do BD são definidas em:", alternativas: ["A) models.py", "B) urls.py", "C) settings.py", "D) wsgi.py"], correta: 0, explicacao: "Models + migrations." },
    { id: "es02", fonte: "CRA-PR 2022", enunciado: "3FN exige que:", alternativas: ["A) não haja dependências transitivas de não chaves", "B) atributos multivalorados", "C) sem chave primária", "D) redundância livre"], correta: 0, explicacao: "Elimina dependência transitiva." },
    { id: "es03", fonte: "CRA-PR 2022", enunciado: "HTTP está na camada:", alternativas: ["A) enlace", "B) rede", "C) transporte", "D) aplicação"], correta: 3, explicacao: "Protocolo de aplicação." },
    { id: "es04", fonte: "Edital 2026", enunciado: "Git: criar branch e mudar para ele:", alternativas: ["A) git merge", "B) git checkout -b nome", "C) git push", "D) git status"], correta: 1, explicacao: "checkout -b ou switch -c." },
    { id: "es05", fonte: "CRA-PR 2022", enunciado: "UML — interações no tempo:", alternativas: ["A) classes", "B) casos de uso", "C) sequência", "D) componentes"], correta: 2, explicacao: "Diagrama de sequência." },
    { id: "es06", fonte: "CRA-PR 2022", enunciado: "SQL para consultar dados:", alternativas: ["A) INSERT", "B) UPDATE", "C) SELECT", "D) DELETE"], correta: 2, explicacao: "SELECT = consulta." },
    { id: "es07", fonte: "Edital 2026", enunciado: "Docker vs VM:", alternativas: ["A) containers compartilham kernel do host", "B) container tem SO completo sempre", "C) VM é mais leve", "D) Docker não isola"], correta: 0, explicacao: "Containers compartilham kernel." },
    { id: "es08", fonte: "CRA-PR 2022", enunciado: "Deadlock ocorre quando:", alternativas: ["A) espera circular por recursos", "B) memória livre em excesso", "C) round-robin ativo", "D) paginação off"], correta: 0, explicacao: "Espera circular bloqueante." },
    { id: "es09", fonte: "CRA-PR 2022", enunciado: "API REST:", alternativas: ["A) só SOAP/XML", "B) stateless + HTTP padronizado", "C) acoplamento forte", "D) sem cache"], correta: 1, explicacao: "Stateless, verbos HTTP." },
    { id: "es10", fonte: "CRA-PR 2022", enunciado: "Identificar riscos no PMBOK — área de:", alternativas: ["A) escopo", "B) riscos", "C) comunicações", "D) aquisições"], correta: 1, explicacao: "Gerenciamento de riscos." },
    { id: "es11", fonte: "CRA-PR 2022", enunciado: "Firewall:", alternativas: ["A) só camada física", "B) filtragem de tráfego de rede", "C) formata disco", "D) compila código"], correta: 1, explicacao: "Controle de tráfego." },
    { id: "es12", fonte: "CRA-PR 2022", enunciado: "O(n log n) típico de:", alternativas: ["A) bubble sort sempre", "B) merge sort", "C) busca linear", "D) inserção desordenada"], correta: 1, explicacao: "Merge sort = O(n log n)." },
    { id: "es13", fonte: "Edital 2026", enunciado: "SaaS significa:", alternativas: ["A) usuário gerencia SO", "B) software pronto via internet", "C) só hardware", "D) sem navegador"], correta: 1, explicacao: "Software as a Service." },
    { id: "es14", fonte: "Edital 2026", enunciado: "IA generativa — governança exige:", alternativas: ["A) só GPU", "B) viés, privacidade e ética", "C) sem auditoria", "D) sem APIs"], correta: 1, explicacao: "Ética e LGPD." },
    { id: "es15", fonte: "Lei 14.133", enunciado: "Termo de Referência (TR) define:", alternativas: ["A) sanções penais", "B) especificações da contratação", "C) eleição interna", "D) registro CRA"], correta: 1, explicacao: "Requisitos do objeto." },
    { id: "es16", fonte: "CRA-PR 2022", enunciado: "ITIL foca em:", alternativas: ["A) gestão de serviços de TI", "B) só hardware", "C) legislação trabalhista", "D) contabilidade"], correta: 0, explicacao: "Best practices de serviços." },
    { id: "es17", fonte: "CRA-PR 2022", enunciado: "Polimorfismo em POO:", alternativas: ["A) mesma interface, comportamentos distintos", "B) elimina herança", "C) proíbe sobrescrita", "D) só globais"], correta: 0, explicacao: "Um método, várias implementações." },
    { id: "es18", fonte: "CRA-PR 2022", enunciado: "Modelo espiral enfatiza:", alternativas: ["A) sem prototipação", "B) análise de riscos por iteração", "C) entrega única", "D) sem revisões"], correta: 1, explicacao: "Riscos em cada ciclo." },
  ],
};
